// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: affiliate.sql

package sqlc

import (
	"context"
	"database/sql"
)

const get_Affiliate_By_UserID = `-- name: Get_Affiliate_By_UserID :one
SELECT 
    id AS affiliate_id,
    user_id,
    campaign_id,
    created_at
FROM affiliates
WHERE user_id = $1
`

type Get_Affiliate_By_UserIDRow struct {
	AffiliateID int64
	UserID      sql.NullInt64
	CampaignID  int64
	CreatedAt   sql.NullTime
}

func (q *Queries) Get_Affiliate_By_UserID(ctx context.Context, userID sql.NullInt64) (Get_Affiliate_By_UserIDRow, error) {
	row := q.db.QueryRowContext(ctx, get_Affiliate_By_UserID, userID)
	var i Get_Affiliate_By_UserIDRow
	err := row.Scan(
		&i.AffiliateID,
		&i.UserID,
		&i.CampaignID,
		&i.CreatedAt,
	)
	return i, err
}
