// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: brand.sql

package sqlc

import (
	"context"
	"database/sql"
)

const get_BrandID_By_TrackingCode = `-- name: Get_BrandID_By_TrackingCode :one
SELECT c.brand_id
FROM tracking_links tl
JOIN campaigns c ON tl.campaign_id = c.id
WHERE tl.link_code = $1
LIMIT 1
`

func (q *Queries) Get_BrandID_By_TrackingCode(ctx context.Context, linkCode string) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, get_BrandID_By_TrackingCode, linkCode)
	var brand_id sql.NullInt64
	err := row.Scan(&brand_id)
	return brand_id, err
}

const get_Brand_By_UserID = `-- name: Get_Brand_By_UserID :one
SELECT 
    b.id, b.user_id, b.company_name, b.website, b.created_at,
    u.username,
    u.email,
    u.role
FROM brands b
JOIN users u ON b.user_id = u.id
WHERE b.user_id = $1
`

type Get_Brand_By_UserIDRow struct {
	ID          int64
	UserID      sql.NullInt64
	CompanyName string
	Website     sql.NullString
	CreatedAt   sql.NullTime
	Username    string
	Email       string
	Role        string
}

func (q *Queries) Get_Brand_By_UserID(ctx context.Context, userID sql.NullInt64) (Get_Brand_By_UserIDRow, error) {
	row := q.db.QueryRowContext(ctx, get_Brand_By_UserID, userID)
	var i Get_Brand_By_UserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.Website,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.Role,
	)
	return i, err
}
