// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Affiliate struct {
	ID         int64
	UserID     sql.NullInt64
	CampaignID int64
	CreatedAt  sql.NullTime
}

type AffiliateCampaign struct {
	AffiliateID int64
	CampaignID  int64
	CreatedAt   sql.NullTime
}

type Brand struct {
	ID          int64
	UserID      sql.NullInt64
	CompanyName string
	Website     sql.NullString
	CreatedAt   sql.NullTime
}

type Campaign struct {
	ID             int64
	BrandID        sql.NullInt64
	Name           string
	Description    sql.NullString
	CommissionRate string
	LandingUrl     string
	CreatedAt      sql.NullTime
}

type Click struct {
	ID             int64
	TrackingLinkID sql.NullInt64
	ClickID        uuid.UUID
	UserIp         string
	UserAgent      sql.NullString
	Referrer       sql.NullString
	Timestamp      sql.NullTime
	UtmSource      sql.NullString
	UtmMedium      sql.NullString
}

type Conversion struct {
	ID        int64
	Amount    float64
	Timestamp sql.NullTime
	Currency  sql.NullString
	ClickID   uuid.NullUUID
	Weight    sql.NullFloat64
}

type Invite struct {
	ID          int64
	CampaignID  int64
	UserID      int64
	Status      string
	InvitedAt   sql.NullTime
	RespondedAt sql.NullTime
}

type Sale struct {
	ID        int64
	BrandID   int64
	Amount    string
	Currency  string
	Timestamp sql.NullTime
	CreatedAt sql.NullTime
}

type Session struct {
	ID           uuid.UUID
	Email        string
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type TrackingLink struct {
	ID          int64
	AffiliateID sql.NullInt64
	CampaignID  sql.NullInt64
	LinkCode    string
	CreatedAt   sql.NullTime
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	// enum: brand, affiliate
	Role      string
	CreatedAt sql.NullTime
}
