// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id,
  email,
  refresh_token,
  user_agent,
  client_ip,
  is_blocked,
  expires_at
) VALUES (
  $1, $2 , $3 , $4 , $5, $6 , $7
) RETURNING id, email, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	ID           uuid.UUID
	Email        string
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Email,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const create_Affiliate = `-- name: Create_Affiliate :one
INSERT INTO affiliates (user_id, created_at)
VALUES ($1, CURRENT_TIMESTAMP)
RETURNING id
`

func (q *Queries) Create_Affiliate(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, create_Affiliate, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const create_Brand = `-- name: Create_Brand :one
INSERT INTO brands (user_id, company_name, website, created_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
RETURNING id
`

type Create_BrandParams struct {
	UserID      sql.NullInt64
	CompanyName string
	Website     sql.NullString
}

func (q *Queries) Create_Brand(ctx context.Context, arg Create_BrandParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, create_Brand, arg.UserID, arg.CompanyName, arg.Website)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const create_User_Affiliate = `-- name: Create_User_Affiliate :one
INSERT INTO users (username, email, password_hash, role, created_at)
VALUES ($1, $2, $3, 'affiliate', CURRENT_TIMESTAMP)
RETURNING id
`

type Create_User_AffiliateParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) Create_User_Affiliate(ctx context.Context, arg Create_User_AffiliateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, create_User_Affiliate, arg.Username, arg.Email, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const create_User_Brand = `-- name: Create_User_Brand :one
INSERT INTO users (username, email, password_hash, role, created_at)
VALUES ($1, $2, $3, 'brand', CURRENT_TIMESTAMP)
RETURNING id
`

type Create_User_BrandParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) Create_User_Brand(ctx context.Context, arg Create_User_BrandParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, create_User_Brand, arg.Username, arg.Email, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSession = `-- name: GetSession :one
SELECT id, email, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const get_User_By_Email = `-- name: Get_User_By_Email :one
SELECT id, username, email, password_hash, role, created_at
FROM users
WHERE email = $1
`

func (q *Queries) Get_User_By_Email(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, get_User_By_Email, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const user_Exists_By_Email = `-- name: User_Exists_By_Email :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) User_Exists_By_Email(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, user_Exists_By_Email, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
